kind: pipeline
type: docker
name: cicd

steps:
  - name: build
    image: openjdk:11
    resources:
      requests:
        cpu: 2000
      limits:
        cpu: 2000
        memory: 2048MiB

  - name: test
    image: se-api
    settings:
      restore: true
    resources:
      requests:
        cpu: 2000
      limits:
        cpu: 2000
        memory: 2048MiB
    commands:
      - chmod +x gradlew
      - ./gradlew test

services:
  - name: mysql-db
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    resources:
      requests:
        cpu: 1000
        memory: 1024MiB
      limits:
        cpu: 1000
        memory: 1024MiB
    ports:
      - 3306

