server:
  port: 8075
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.0.1:33067/se_file_server_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: se_file_server_guest
    password: 1q2w3e4r!
    admin:
      id: admin
      password: se75407540
      name: admin
      nickname: admin
      studentId: 0
      email: test@kumoh.ac.kr

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true

  security:
    user:
      name: test
      password: test
    anonymous:
      id: 0
      pw: ANM
  jwt:
    secret: se7540
    default-group: ANONYMOUS
    header: X-AUTH-TOKEN

logging:
  level:
    org:
      hibernate: info
    com:
      se:
        se_file_server:
          file: debug

se-file-server:
  upload-dir: /var/se-file-server   # for linux
  max-file-size : 500000000

se-web-server:
  file-dash-server-domain: http://file-dash.se-testboard.duckdns.org